# Generated by Django 2.2.5 on 2019-09-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date'], 'permissions': (('can_write_comment', 'Can comment'),)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date'], 'permissions': (('can_write_post', 'Can write posts'),)},
        ),
    ]
